Added a pull request template
avinashkranjan/Recess pull request #78
Opened 2021-03-10 21:08 UTC by kanak22

I have added a pull request template.
This PR will close the issue : #63

2021-03-11 14:57 UTC, avinashkranjan requested changes
Add a Section to add SS of the made changes

2021-03-11 18:46 UTC, kanak22 commented
I did the asked change.

2021-03-14 06:39 UTC, Utkarsh1999 approved these changes

2021-03-14 21:34 UTC, avinashkranjan approved these changes

2021-03-14 21:35 UTC, merged

2021-03-14 21:36 UTC, avinashkranjan commented
@all-contributors please add @kanak22 for documentation