Changes made in Navigation Bar-Issue#77 Addressed
avinashkranjan/Recess pull request #90
Opened 2021-03-12 09:36 UTC by AnjaliSrivastava722

Text on buttons changed and spacing adjusted.

2021-03-14 06:28 UTC, Utkarsh1999 requested changes
Hi @AnjaliSrivastava722 ,
1. remove extra blank lines (line no. 35 and 36) from Homepage.js
2. change button text from All caps to Capitalise i.e LOGIN->Login and SIGNUP -> Sign Up

2021-03-14 08:17 UTC, AnjaliSrivastava722 commented
Made the required changes please merge my request.Thank You.

2021-03-15 07:29 UTC, Utkarsh1999 approved these changes

2021-03-16 16:02 UTC, merged

2021-03-16 16:02 UTC, avinashkranjan commented
@all-contributors please add @AnjaliSrivastava722  for code